import { config } from "dotenv";
config({ path: `.env` });

export const CREDENTIALS = process.env.CREDENTIALS === "true";
export const {
  NODE_ENV,
  PORT,
  SECRET_KEY,
  LOG_FORMAT,
  LOG_DIR,
  ORIGIN,
  JWT_EXPIRES_IN,
} = process.env;
export const {
  FIREBASE_AUTH_PROVIDER_X509_CERT_URL,
  FIREBASE_AUTH_URI,
  FIREBASE_CLIENT_EMAIL,
  FIREBASE_CLIENT_ID,
  FIREBASE_CLIENT_X509_CERT_URL,
  FIREBASE_PRIVATE_KEY,
  FIREBASE_PRIVATE_KEY_ID,
  FIREBASE_PROJECT_ID,
  FIREBASE_TOKEN_URI,
  FIREBASE_TYPE,
} = process.env;
export const { DB_NAME, DB_HOST, DB_PASSWORD, DB_USER } = process.env;

export const {
  AWS_ACCESS_KEY_ID,
  AWS_REGION,
  AWS_S3_BUCKET_NAME,
  AWS_SECRET_ACCESS_KEY,
} = process.env;
export const {
  FRONT_END_URL,
  SEND_GRID_API_KEY_1,
  SEND_GRID_API_KEY_2,
  SEND_GRID_API_KEY_3,
} = process.env;


export const {
  PAYFAST_MERCHANT_ID ,
  PAYFAST_MERCHANT_KEY ,
  PAYFAST_NOTIFY_URL ,
  PAYFAST_RETURN_URL ,
  PAYFAST_CANCEL_URL,
  PAYFAST_PAYMENT_URL ,
  PAYFAST_STATUS_URL ,
  PAYFAST_PASSPHRASE,
  PAYFAST_ENV,
  

} = process.env